sudo: required
services:
  - docker

before_install:
  - docker build -t raseshwari/react-test -f ./client/Dockerfile.dev ./client

# primary test running section is script
script:
  - docker run raseshwari/react-test npm test --  ----coverage #override to run with npm test and --coverage to eventually exit
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t raseshwari/multi-client ./client #./client is the build context
  - docker build -t raseshwari/multi-nginx ./nginx #./nginx is the build context
  - docker build -t raseshwari/multi-server ./server #./server is the build context
  - docker build -t raseshwari/multi-worker ./worker #./worker is the build context

